name: Deploy backend to the server

on: 
  push:
    branches: [main]

jobs:
  build_compile_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo code
        uses: actions/checkout@v2
        
      - name: Login to docker hub
        uses: docker/login-action@v4
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Build and push to backend image - docker hub
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./docker/Dockerfile.backend
          push: true
          # tags: sartajashraf/basic-1.0-docker-node-deploy-backend:latest
          tags: sartajashraf/basic-1.0-docker-node-deploy-backend:${{ github.sha }}
      - name: SSH and Deploy to the server
        run:  |
          echo "next step to run "