name: Deploy backend to the server

on: 
  push:
    branches: [main]

jobs:
  build_compile_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo code
        uses: actions/checkout@v2
        
      - name: Login to docker hub
        uses: docker/login-action@v4
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Build and push to backend image - docker hub
        uses: docker/build-push-action@v2
        with:
          context: backend
          file: ./docker/Dockerfile.backend
          push: true
          tags: sartajashraf/basic-1.0-docker-node-deploy-backend:latest

      # - name: SSH and Deploy to the server
      #   uses: appleboy/ssh-action@v1.0.3
      #   with:
      #     host: ${{ secrets.SSH_HOST_IP }}
      #     username: ${{ secrets.SSH_HOST_USER }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     script: |
      #       docker pull sartajashraf/basic-1.0-docker-node-deploy-backend:latest
      #       docker stop basic-1.0-docker-node-deploy-backend || true
      #       docker rm basic-1.0-docker-node-deploy-backend || true
      #       docker run -d --name basic-1.0-docker-node-deploy-backend -p 5030:5030 sartajashraf/basic-1.0-docker-node-deploy-backend:latest
      - name: SSH into server and deploy
        run: |
          mkdir -p ~/.ssh
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/auth_private_key
          chmod 600 ~/.ssh/auth_private_key


          ssh -i ~/.ssh/auth_private_key \
            -o StrictHostKeyChecking=no \
            ${{ secrets.SSH_HOST_USER }}@${{ secrets.SSH_HOST_IP }} << 'EOF'
           
            IMAGE="sartajashraf/basic-1.0-docker-node-deploy-backend:latest"
            CONTAINER="basic-1.0-docker-node-deploy-backend"

            echo "Pull latest image"
            docker pull "$IMAGE"

            if docker ps -q -f name="$CONTAINER" | grep -q .; then
              echo "Stopping and removing existing container"
              docker stop "$CONTAINER"
              docker rm "$CONTAINER"
            fi

          echo "Starting new container..."
          docker run -d \
            --name "$CONTAINER" \
            --restart unless-stopped \
            -p 5030:5030 \
            "$IMAGE"
            
            echo "Deployment completed successfully."
          EOF
            
          